### PR TITLE
fix: update render flow type with new option unstable_validateStringsRenderedWithinText

### PR DESCRIPTION
**Pull request by pierrezimmermannbam**
### Summary

Adds new option unstable_validateStringsRenderedWithinText to renderOptions type in flow types

### Test plan

I don't know how to test flow types, is there a recommended way to do so ?

### CODE REVIEW

**Review by mdjastrzebski — APPROVED** [review]
👍🏻

**Comment by mdjastrzebski** [comment]
We have `flow` check but it only checks is typedef is syntactically correct. There is no check that would verify whether the flow types match TS code.

**Comment by AugustinLF** [comment]
Just move it to flow-typed and it's not our problem anymore 👀

**Comment by AugustinLF** [comment]
Yeah I know, was just saying that for the next one ;)

**Pull request merged**
