### PR TITLE
feat: add renderHook function

### PR DESCRIPTION
**Pull request by pierrezimmermannbam**
### Summary

This pr provides a basic implementation of renderHook as requested in #869. The solution is almost a copy past from the one made in react testing library

### Test plan

Some test cases were added, also inspired from the implementation from react testing library

### CODE REVIEW

**Comment by AugustinLF** [comment]
The `@testing-library/react` [PR](https://github.com/testing-library/react-testing-library/pull/991) still hasn't been merged, so I'd like for it to be merged first before getting that in. I'm monitoring said PR, but don't hesitate to ping me once it's merged if I miss it.

**Comment by mpeyper** [comment]
The RTL PR has been merged now. Please let me know if there is anything I can do to progress this.

**Review by AugustinLF — CHANGES_REQUESTED** [review]
Implementation and tests look correct to me. Could you fix the conflicts and also add documentation for it in https://github.com/callstack/react-native-testing-library/blob/main/website/docs/API.md

**Comment by pierrezimmermannbam** [comment]
I'm working on migrating to typescript, I'll add documentation afterwards, it shouldn't take long

**Comment by pierrezimmermannbam** [comment]
It's done, there is a typing issue because the option param is optional so initialProps may not be defined when it needs to be but changing the typing would mean having a different api from the one of react-hooks-testing-library and I'm not sure it's something we want. 

I also added documentation, I used the documentation I found on the react-hooks-testing-library repo and added some examples

**Comment by AugustinLF** [comment]
Oops forgot to ask for flow types https://github.com/callstack/react-native-testing-library/blob/main/typings/index.flow.js But after that we should be good I believe

**Comment by pierrezimmermannbam** [comment]
@AugustinLF I added the flow types

**Review by AugustinLF — APPROVED** [review]

**Review by thymikee — APPROVED** [review]
Pushed some documentation updates. Looking pretty!

**Pull request merged**
