### PR TITLE
feature: better support for hooks

### LINKED ISSUE #111: Wrap render calls with act() for better Hooks integration
Hooks work fine even without it, but you'll likely need to add asynchrony to your code. With `act()` you'll be able to achieve the same results in synchronous manner.

See: https://reactjs.org/blog/2019/02/06/react-v16.8.0.html#testing-hooks

### PR DESCRIPTION
**Pull request by Esemesek**
### Summary

Make testing hooks easy.

- [x] - `render` calls are wrapped with `act`
- [x] - `fireEvent` calls are wrapped with `act`
- [x] - re-exported `act` from `react-test-renderer`
- [x] - added mock `act` function to prevent brakeable changes
- [x] - added docs
- [x] - updated typescript definitions
- [x] - added tests

### Test plan

Unit tests are included in PR.

Fixes #111

### CODE REVIEW

**Comment by hyochan** [comment]
I was waiting for this! Hope current `PR` to be merged and released as soon as possible.

**Comment by Esemesek** [comment]
@hyochan I want it to be checked by @thymikee, but he is on vacations right now. It should be merged in a week time C:

**Comment by hyochan** [comment]
@Esemesek No worry. I can hold that amount of time. Thank you for the detail.

**Comment by hyochan** [comment]
@thymikee Thanks. Hope I can get notified when this is released.

**Comment by thymikee** [comment]
It's up in 1.6.0, enjoy :)

**Comment by hyochan** [comment]
@thymikee @Esemesek I am sorry that I may have to ask this question here. I'd really want to know how to test the `useEffect` as in `react-testing-library` like in [tutorial](https://egghead.io/lessons/react-test-effects-generated-from-react-the-useeffect-hook). How could I achieve things like `rerender` in `react-native-testing-library`?

**Comment by thymikee** [comment]
@hyochan it just _just work_ now that all `render`s are wrapped with `act` – look at the test file:

https://github.com/callstack/react-native-testing-library/blob/b3abf50a108dfd9e981375640189e934ddeecd0e/src/__tests__/act.test.js#L9-L29

Apart from that, we don't have `rerender`, but we have `update` method that works the same, see: https://reactjs.org/docs/test-renderer.html#testrendererupdate

**Comment by hyochan** [comment]
@thymikee Thank you so much for your attention! I get it now.

**Pull request merged**
