### PR TITLE
fix: check for undefined/null children

### LINKED ISSUE #135: [1.6.1] Cannot read property 'toString' of null
## Versions

- Expo v32.0.0
- jest-expo v32.0.0
- React v16.5.0
- NativeBase v2.12.1
- react-native-testing-library v1.6.1
- react-test-renderer v16.8.4
- OS: multiple

## Description

As of v1.6.1, I am receiving the following error when trying to test a NativeBase `Picker` using `getByText` (the same tests pass in v1.6.0):

```
Currently the only supported library to search by text is "react-native".

Cannot read property 'toString' of null
```
This only seems to happen when there are **multiple tests**.

## Reproducible Demo

https://github.com/wKovacs64/rntl-161-repro

### PR DESCRIPTION
**Pull request by Esemesek**
### Summary

Check for undefined/null values, in `getByText` nodes.

Fixes #135 

### Test plan

Passing tests on repro repository https://github.com/wKovacs64/rntl-161-repro.

Have no idea how to create a unit test, to test this behavior.

cc @thymikee @wKovacs64

### CODE REVIEW

**Comment by wKovacs64** [comment]
This works in my much larger "real" app, too! 🎉 

---

Out of curiosity, how were you testing this branch in the repro repo? `yarn link` didn't work for me for some reason, I had to manually copy the build output.

<details>
<summary><code>yarn link</code> results</summary>

#### First test:
```
Currently the only supported library to search by text is "react-native".

Cannot find module 'warnOnce' from 'react-native-implementation.js'
```

#### Second test:
```
No instances found
```

</details>

**Comment by thymikee** [comment]
Did you run `yarn` so that the files are updated in the `build/` dir?

**Comment by wKovacs64** [comment]
I did indeed.

**Comment by Esemesek** [comment]
@wKovacs64 
- Install deps
- Go to `node_modules/react-native-testing-library`
- Change `"main"` in `package.json` to point to `src/index.js` instead of `build/index.js`
- Edit files in `node_modules/react-native-testing-library/src` and hack around :P

**Comment by wKovacs64** [comment]
@Esemesek Thanks. 🙂

**Comment by steobrien** [comment]
Thanks a lot for this fix! Looking forward to seeing it in a release.

**Comment by jakemmarsh** [comment]
Any updates on getting this published?

**Comment by ryanjwessel** [comment]
Not sure if this has been integrated with a release yet, but I am running into this error on version 7.0.1 today.

**Pull request merged**
