### PR TITLE
Compile to ES5

### PR DESCRIPTION
**Pull request by Jukkish**
### Summary

Fixes https://github.com/callstack/react-native-testing-library/issues/49

### CODE REVIEW

**Comment by thymikee** [comment]
Thanks! I've adjusted the PR a bit. We don't use `npm`, so no `package-lock.json`.

**Comment by Jukkish** [comment]
Thanks!

**Comment by thymikee** [comment]
Um, it's not merged yet?

**Comment by Jukkish** [comment]
> Um, it's not merged yet?

Sry, it was an accident :D

**Comment by Esemesek** [comment]
Looks good to me. We still need to investigate if `flow` types are working correctly with this configuration.

**Comment by thymikee** [comment]
They're not. We're gonna need something like https://github.com/Macil/flow-copy-source

**Comment by henrikra** [comment]
Side note: does it make sense to have tests inside src folder? Usually tests are on root level 🤔

**Comment by thymikee** [comment]
Of course it does! The same way as having them in the root level or side-by-side to your source files 😉

**Comment by henrikra** [comment]
Can we get this merged? 😀

**Comment by thymikee** [comment]
Not yet, we need to figure out exporting Flow types, would like to avoid duplication where possible.

**Pull request merged**
