### PR TITLE
Add getInstance helper

### PR DESCRIPTION
**Pull request by benadamstyles**
This allows testing `instance.state` and other advanced patterns using the component instance.

### CODE REVIEW

**Comment by benadamstyles** [comment]
(Obviously I'm happy to writes tests and types, I just wanted to get feedback on the idea first!)

**Comment by thymikee** [comment]
Sorry to be a bearer of "bad" news, but this is a design decision behind this library not to export getInstance. Testing internal component instance is basically testing implementation details. If you have parts of the state management that you'd like to test e.g. for edge cases, export that piece of functionality and test in isolation. 

I'm thankful for the PR though, that's great attitude!

**Comment by benadamstyles** [comment]
Fair enough, no problem! Maybe you should change the docs [here](https://github.com/callstack/react-native-testing-library#render) which state:

> For convenience it also returns react-test-renderer's instance and renderer objects, in case you need more control.

That actually isn't the case, but it made me think that you might be open to adding that functionality back in.

**Comment by thymikee** [comment]
Ahh forgot to remove that! Would you like to send a PR?

**Pull request closed without merging**
